"""
Project Euler Problem 2

Title:
Even Fibonacci numbers

Description:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.

Solution:
Naive solution: loop through the Fibonacci sequence while adding the even numbers in the series along the away.

Answer: 4613732
I'm the 258033rd person to solve this problem.

"""
MAX = 4000000
a = 1
b = 2
c = 0
sum = 2

while c < MAX:
    c = a + b

    if c % 2 == 0:
        sum += c

    a = b
    b = c

sum -= c

print sum